# Generated by Django 5.2 on 2025-04-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carr', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nome',
            new_name='name',
        ),
    ]
